%% Per iteration SNR for different # of projections
%

algs = {
  % ASTRA types
  %
  struct('name','SART', 'type','astra', 'clr','-kd', ...
    'alg','SART', ...
    'alg_params', struct('iter',iter, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',1, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0)))

  struct('name','BSSART', 'type','astra', 'clr','-.ko', ...
    'alg','SART', ...
    'alg_params', struct('iter',iter, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',1, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',1)))

  struct('name','ART', 'type','astra', 'clr','-rs', ...
    'alg','ART', ...
    'alg_params', struct('iter',iter, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',1, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0)))

  struct('name','SIRT', 'type','astra', 'clr','-bx', ...
    'alg','SIRT', ...
    'alg_params', struct('iter',iter, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',1, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0)))

  struct('name','BICAV', 'type','astra', 'clr','-g*', ...
    'alg','BICAV', ...
    'alg_params', struct('iter',iter, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',1, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0)))

  struct('name','OS-SQS', 'type','astra', 'clr','-m^', ...
    'alg','OS-SQS', ...
    'alg_params', struct('iter',iter, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',1, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0)))

  struct('name','CGLS', 'type','astra', 'clr','-cv', ...
    'alg','CGLS', ...
    'alg_params', struct('iter',iter, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',2, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0)))      
  };

args = struct('phan','sl', 'phan_size',512, 'path','./plots', ...
  'noise_type','gauss', 'noise_level',0.01, 'num_proj',30, ...
  'iter',40);

ma_fig_periter(arg, algs);

%%