%% Actual Shepp Logan phantom
SL = [  2   .69   .92    0     0     0   
        -.98 .6624 .8740   0  -.0184   0
        -.02 .1100 .3100  .22    0    -18
        -.02 .1600 .4100 -.22    0     18
         .01 .2100 .2500   0    .35    0
         .01 .0460 .0460   0    .1     0
         .01 .0460 .0460   0   -.1     0
         .01 .0460 .0230 -.08  -.605   0 
         .01 .0230 .0230   0   -.606   0
         .01 .0230 .0460  .06  -.605   0   ];
P = phantom(SL, 512);
save phantoms/sl-512.mat P
% imwrite(P, 'sl-256.png', 'BitDepth',16);

%% Modified Shepp-Logan
P = phantom(512);
save phantoms/mod-sl-512.mat P

%% Ncat
% How it was generated
% 	imgBig = read_ncat('nx', 1024, 'ny', 1024, 'marrow', true, ...
% 		'mu', [0 0.05 0.2 0.4 0.4 0.2]/0.2*1000); % True highres NCAT
% 	imgBig = single(imgBig) / single(max(imgBig(:))) * 0.4; % convert to 1/cm units

scale = 512;
P = read_ncat('nx', scale, 'ny', scale, 'marrow', true, ...
  'mu', [0 0.05 0.2 0.4 0.4 0.2]/0.2*1000); % True highres NCAT
P = single(P') / single(max(P(:))) * 0.4; % convert to 1/cm units

save(sprintf('phantoms/ncat-%d.mat', scale), 'P')
%% Not using this anymore
load phantoms/ncat-1024.mat
figure(1), imshow(P, [])

scale = 256;
P = imresize(P, scale / 1024, 'lanczos3');
figure(2), imshow(P, []), colorbar
P(P<0) = 0;
save(sprintf('phantoms/ncat-%d.mat', scale), 'P')

%% Algorithms for initial comparison of iterative methods
% namely ART, SART, SIRT, BICAV, BSSART, OS-SQS
%

algs = {
  % ASTRA types
  %
  struct('name','SART', 'type','astra', ...
    'clr','k', 'lstyle','-', 'marker','d', ...
    'alg','SART', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',1, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0, 'ProjectionOrder','sequential')))
      
  struct('name','SART-1.99', 'type','astra', ...
    'clr','k', 'lstyle','--', 'marker','d', ...
    'alg','SART', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',1.99, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0, 'ProjectionOrder','sequential')))

  struct('name','SART-0.1', 'type','astra', ...
    'clr','k', 'lstyle',':', 'marker','d', ...
    'alg','SART', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',.1, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0, 'ProjectionOrder','sequential')))
      
  struct('name','BSSART', 'type','astra', ...
    'clr',[1 0.5 0], 'lstyle','-', 'marker','d', ...
    'alg','SART', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',1, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',1, 'ProjectionOrder','sequential')))

  struct('name','BSSART-1.99', 'type','astra', ...
    'clr',[1 0.5 0], 'lstyle','--', 'marker','d', ...
    'alg','SART', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',1.99, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',1, 'ProjectionOrder','sequential')))
      
  struct('name','BSSART-0.1', 'type','astra', ...
    'clr',[1 0.5 0], 'lstyle',':', 'marker','d', ...
    'alg','SART', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',0.1, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',1, 'ProjectionOrder','sequential')))
      
  struct('name','ART', 'type','astra', ...
    'clr','r', 'lstyle','-', 'marker','s', ...
    'alg','ART', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',1, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0, 'ProjectionOrder','sequential')))

	struct('name','ART-1.99', 'type','astra', ...
    'clr','r', 'lstyle','--', 'marker','s', ...
    'alg','ART', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',1.99, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0, 'ProjectionOrder','sequential')))

	struct('name','ART-0.1', 'type','astra', ...
    'clr','r', 'lstyle',':', 'marker','s', ...
    'alg','ART', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',.1, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0, 'ProjectionOrder','sequential')))
      
  struct('name','SIRT', 'type','astra', ...
    'clr','b', 'lstyle','-', 'marker','x', ...
    'alg','SIRT', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',1, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0, 'ProjectionOrder','sequential')))

  struct('name','SIRT-1.99', 'type','astra', ...
    'clr','b', 'lstyle','--', 'marker','x', ...
    'alg','SIRT', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',1.99, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0, 'ProjectionOrder','sequential')))

  struct('name','SIRT-0.1', 'type','astra', ...
    'clr','b', 'lstyle',':', 'marker','x', ...
    'alg','SIRT', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',0.1, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0, 'ProjectionOrder','sequential')))
      
	struct('name','BICAV', 'type','astra', ...
    'clr','g', 'lstyle','-', 'marker','*', ...
    'alg','BICAV', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',1, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0, 'ProjectionOrder','sequential')))

	struct('name','BICAV-1.99', 'type','astra', ...
    'clr','g', 'lstyle','--', 'marker','*', ...
    'alg','BICAV', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',1.99, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0, 'ProjectionOrder','sequential')))
      
	struct('name','BICAV-0.1', 'type','astra', ...
    'clr','g', 'lstyle',':', 'marker','*', ...
    'alg','BICAV', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',0.1, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0, 'ProjectionOrder','sequential')))
      
  struct('name','OS-SQS', 'type','astra', ...
    'clr','m', 'lstyle','-', 'marker','^', ...
    'alg','OS-SQS', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',1, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0, 'ProjectionOrder','sequential')))

  struct('name','OS-SQS-0.1', 'type','astra', ...
    'clr','m', 'lstyle',':', 'marker','^', ...
    'alg','OS-SQS', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',.1, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0, 'ProjectionOrder','sequential')))
      
%   struct('name','OS-SQS-0.5', 'type','astra', 'clr','-r^', ...
%     'alg','OS-SQS', ...
%     'alg_params', struct('iter',1, ...
%       'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
%       'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
%       'Alpha',0.5, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
%       'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
%       'UseBSSART',0)))
% 
%   struct('name','OS-SQS-0.1', 'type','astra', 'clr','-g^', ...
%     'alg','OS-SQS', ...
%     'alg_params', struct('iter',1, ...
%       'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
%       'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
%       'Alpha',.1, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
%       'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
%       'UseBSSART',0)))
      
  struct('name','CGLS', 'type','astra', ...
    'clr',[0.5 0.5 0.5], 'lstyle','-', 'marker','v', ...
    'alg','CGLS', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',2, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0, 'ProjectionOrder','sequential')))
  };

%% Algorithms for proximal comparison with alpha=1: 
% SART, ART, BICAV, OS-SQS%

algs = {
  % PSART types
  %
  struct('name','ADMM-SART-L2-ATV', 'type','psart', ...
    'clr','b', 'lstyle','-', 'marker','v', ...
    'alg','admm', ...
    'alg_params', struct('iter',1, 'sigma',25, 'rho',10, 'mu',[], ...1/(8*rho), ... 40&3 (no fbp) 100&5 (fbp)
      'theta',1, 'init_fbp',1, 'data','l2', 'prior','atv', ...
      'sigma_with_data', 1, 'prox','astra', 'prox_name','SART-PROX', ...
      'prox_params', struct('iter',2, ...
        'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
          'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
          'Alpha',2, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
          'ClearReconstruction',1, ...
          'UseBSSART',0, 'ProjectionOrder','sequential'))))

  % IRT types
  %
  struct('name','Ramani-ADMM', 'type','irt', ...
    'clr',[0.5 0.5 0.5], 'lstyle','-', 'marker','p', ...
    'alg','admm', ...
    'alg_params', struct('iter',1, 'mu',1e-3, 'nCG',2, 'lambda',1e-2, ... .001&.01
      'nu',200, 'operator','W', 'prior_type','l1', 'precon',1, ... %nu=200
      'init_fbp',1, 'minx',0, 'wls',0))
  
  % ASTRA types
  %
  struct('name','SART', 'type','astra', ...
    'clr','k', 'lstyle','-', 'marker','d', ...
    'alg','SART-PROX', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',2, 'Lambda',1e10, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0, 'ProjectionOrder','sequential')))
      
  struct('name','SART-10', 'type','astra', ...
    'clr','k', 'lstyle','--', 'marker','d', ...
    'alg','SART-PROX', ...
    'alg_params', struct('iter',1, 'wls',1,...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',2, 'Lambda',0.5e-1, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0, 'ProjectionOrder','sequential')))
      
  struct('name','ART', 'type','astra', ...
    'clr','r', 'lstyle','-', 'marker','s', ...
    'alg','ART-PROX', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',2, 'Lambda',1e10, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0, 'ProjectionOrder','sequential')))

	struct('name','ART-10', 'type','astra', ...
    'clr','r', 'lstyle','--', 'marker','s', ...
    'alg','ART-PROX', ...
    'alg_params', struct('iter',1, 'wls',1,...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',2, 'Lambda',0.5e1, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0, 'ProjectionOrder','sequential')))
      
	struct('name','BICAV', 'type','astra', ...
    'clr','g', 'lstyle','-', 'marker','*', ...
    'alg','BICAV-PROX', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',2, 'Lambda',1e10, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0, 'ProjectionOrder','sequential')))

	struct('name','BICAV-10', 'type','astra', ...
    'clr','g', 'lstyle','--', 'marker','*', ...
    'alg','BICAV-PROX', ...
    'alg_params', struct('iter',1, 'wls',1,...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',2, 'Lambda',0.5e1, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0, 'ProjectionOrder','sequential')))
      
  struct('name','OS-SQS', 'type','astra', ...
    'clr','m', 'lstyle','-', 'marker','^', ...
    'alg','OS-SQS-PROX', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',1, 'Lambda',1e10, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0, 'ProjectionOrder','sequential')))

  struct('name','OS-SQS-10', 'type','astra', ...
    'clr','m', 'lstyle','--', 'marker','^', ...
    'alg','OS-SQS-PROX', ...
    'alg_params', struct('iter',1, 'wls',1,...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',1, 'Lambda',0.5e1, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0, 'ProjectionOrder','sequential')))
  };

phantoms = {'mod-sl'}; {'ncat', 'mod-sl'}; {'ncat', 'mod-sl'}; {'mod-sl', 'ncat'}; {'ncat', 'mod-sl'}; {'mouse'}; {'ncat', 'mod-sl'};
num_projs = 30; [15, 90]; [15, 30, 60, 90, 180]; 
noises = { 
  struct('noise_type', 'poisson', 'noise_levels',[1e5])}; %, ... 5e4 1e4]), ...
%   struct('noise_type', 'gauss', 'noise_levels',[0.0])}; %.005 .01 .05 .1])}; %0.001 .003 .005 .01]) 
  
% noise_type = 'poisson'; 'poisson'; {'gauss'};
% noise_levels = 1e5; %[0, .005, .01, .05, .1]; %.001  1e5 for poisson
proj_types = {'fan'}; %{'fan', 'parallel', 'mouse'};
iter = 6;
prefix = 'prox';
plt = 'per_iter';

for phantom = phantoms
  for num_proj = num_projs
    for noise = noises
      noise_type = noise{1}.noise_type;
      for noise_level = noise{1}.noise_levels
        for proj_type = proj_types
          % put args
          arg = struct('phan',phantom, 'phan_size',512, 'path','./plots', ...
            'noise_type',noise_type, 'noise_level',noise_level, ...
            'num_proj',num_proj, 'iter',iter, 'recompute',1, ...
            'proj_type',proj_type, 'prefix',prefix, 'plot_resid',0, ...
            'legend_cols',2, 'per_time',0, 'prox_fbp',0);
          % call
          ma_run_and_plot(plt, arg, algs(1:2));
        end
      end
    end
  end
end

%% Comparison of different data terms, priors using SART-PROX and ADMM

algs = {
  % Basic SART
  struct('name','SART', 'type','astra', ...
    'clr','k', 'lstyle','-', 'marker','d', ...
    'alg','SART', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',2, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0, 'ProjectionOrder','sequential')))
  
  % PSART types
  %
  struct('name','Gauss-ITV', 'type','psart', ...
    'clr','b', 'lstyle','-', 'marker','o', ...
    'alg','admm', ...
    'alg_params', struct('iter',1, 'sigma',25, 'rho',10, 'mu',[], ...1/(8*rho), ... 40&3 (no fbp) 100&5 (fbp)
      'theta',1, 'init_fbp',0, 'data','l2', 'prior','itv', ...
      'sigma_with_data', 1, 'prox','astra', 'prox_name','SART-PROX', ...
      'prox_params', struct('iter',2, ...
        'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
          'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
          'Alpha',2, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
          'ClearReconstruction',1, ...
          'UseBSSART',0, 'ProjectionOrder','sequential'))))

  struct('name','Gauss-ATV', 'type','psart', ...
    'clr','r', 'lstyle','-', 'marker','o', ...
    'alg','admm', ...
    'alg_params', struct('iter',1, 'sigma',25, 'rho',10, 'mu',[], ...1/(8*rho), ... 40&3 (no fbp) 100&5 (fbp)
      'theta',1, 'init_fbp',0, 'data','l2', 'prior','atv', ...
      'sigma_with_data', 1, 'prox','astra', 'prox_name','SART-PROX', ...
      'prox_params', struct('iter',2, ...
        'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
          'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
          'Alpha',2, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
          'ClearReconstruction',1, ...
          'UseBSSART',0, 'ProjectionOrder','sequential'))))

  struct('name','Gauss-SAD', 'type','psart', ...
    'clr','g', 'lstyle','-', 'marker','o', ...
    'alg','admm', ...
    'alg_params', struct('iter',1, 'sigma',25, 'rho',10, 'mu',[], ...1/(8*rho), ... 40&3 (no fbp) 100&5 (fbp)
      'theta',1, 'init_fbp',0, 'data','l2', 'prior','sad', ...
      'sigma_with_data', 1, 'prox','astra', 'prox_name','SART-PROX', ...
      'prox_params', struct('iter',2, ...
        'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
          'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
          'Alpha',2, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
          'ClearReconstruction',1, ...
          'UseBSSART',0, 'ProjectionOrder','sequential'))))
          
  struct('name','Poiss-ITV', 'type','psart', ...
    'clr','b', 'lstyle',':', 'marker','s', ...
    'alg','admm', ...
    'alg_params', struct('iter',1, 'sigma',25, 'rho',10, 'mu',[], ...1/(8*rho), ... 40&3 (no fbp) 100&5 (fbp)
      'theta',1, 'init_fbp',0, 'data','wls', 'prior','itv', ...
      'sigma_with_data', 1, 'prox','astra', 'prox_name','SART-PROX', ...
      'prox_params', struct('iter',2, ...
        'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
          'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
          'Alpha',2, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
          'ClearReconstruction',1, ...
          'UseBSSART',0, 'ProjectionOrder','sequential'))))

  struct('name','Poiss-ATV', 'type','psart', ...
    'clr','r', 'lstyle',':', 'marker','s', ...
    'alg','admm', ...
    'alg_params', struct('iter',1, 'sigma',25, 'rho',10, 'mu',[], ...1/(8*rho), ... 40&3 (no fbp) 100&5 (fbp)
      'theta',1, 'init_fbp',0, 'data','wls', 'prior','atv', ...
      'sigma_with_data', 1, 'prox','astra', 'prox_name','SART-PROX', ...
      'prox_params', struct('iter',2, ...
        'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
          'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
          'Alpha',2, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
          'ClearReconstruction',1, ...
          'UseBSSART',0, 'ProjectionOrder','sequential'))))

  struct('name','Poiss-SAD', 'type','psart', ...
    'clr','g', 'lstyle',':', 'marker','s', ...
    'alg','admm', ...
    'alg_params', struct('iter',1, 'sigma',25, 'rho',10, 'mu',[], ...1/(8*rho), ... 40&3 (no fbp) 100&5 (fbp)
      'theta',1, 'init_fbp',0, 'data','wls', 'prior','sad', ...
      'sigma_with_data', 1, 'prox','astra', 'prox_name','SART-PROX', ...
      'prox_params', struct('iter',2, ...
        'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
          'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
          'Alpha',2, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
          'ClearReconstruction',1, ...
          'UseBSSART',0, 'ProjectionOrder','sequential'))))
          
  };

phantoms = {'ncat'}; {'ncat', 'mod-sl'}; {'ncat', 'mod-sl'}; {'mod-sl', 'ncat'}; {'ncat', 'mod-sl'}; {'mouse'}; {'ncat', 'mod-sl'};
num_projs = 30; [15, 90]; [15, 30, 60, 90, 180]; 
noises = { 
  struct('noise_type', 'poisson', 'noise_levels',[1e5])}; %, ... 5e4 1e4]), ...
%   struct('noise_type', 'gauss', 'noise_levels',[0.0])}; %.005 .01 .05 .1])}; %0.001 .003 .005 .01]) 
  
% noise_type = 'poisson'; 'poisson'; {'gauss'};
% noise_levels = 1e5; %[0, .005, .01, .05, .1]; %.001  1e5 for poisson
proj_types = {'fan'}; %{'fan', 'parallel', 'mouse'};
iter = 4;
prefix = 'sart-prox-comp-';
plt = 'per_iter';

for phantom = phantoms
  for num_proj = num_projs
    for noise = noises
      noise_type = noise{1}.noise_type;
      for noise_level = noise{1}.noise_levels
        for proj_type = proj_types
          % put args
          arg = struct('phan',phantom, 'phan_size',512, 'path','./plots', ...
            'noise_type',noise_type, 'noise_level',noise_level, ...
            'num_proj',num_proj, 'iter',iter, 'recompute',1, ...
            'proj_type',proj_type, 'prefix',prefix, 'plot_resid',0, ...
            'legend_cols',2, 'per_time',0, 'prox_fbp',0);
          % call
          ma_run_and_plot(plt, arg, algs(1:2));
        end
      end
    end
  end
end


%% Per Iteration
phantoms = {'mouse'}; {'ncat', 'mod-sl'}; {'ncat', 'mod-sl'}; {'mod-sl', 'ncat'}; {'ncat', 'mod-sl'}; {'mouse'}; {'ncat', 'mod-sl'};
num_projs = 90; [15, 90]; [15, 30, 60, 90, 180]; 
noises = { 
%   struct('noise_type', 'poisson', 'noise_levels',[1e5])}; %, ... 5e4 1e4]), ...
  struct('noise_type', 'gauss', 'noise_levels',[0.0])}; %.005 .01 .05 .1])}; %0.001 .003 .005 .01]) 
  
% noise_type = 'poisson'; 'poisson'; {'gauss'};
% noise_levels = 1e5; %[0, .005, .01, .05, .1]; %.001  1e5 for poisson
proj_types = {'mouse'}; %{'fan', 'parallel', 'mouse'};
iter = 30;
prefix = '';
plt = 'per_iter';

for phantom = phantoms
  for num_proj = num_projs
    for noise = noises
      noise_type = noise{1}.noise_type;
      for noise_level = noise{1}.noise_levels
        for proj_type = proj_types
          % put args
          arg = struct('phan',phantom, 'phan_size',512, 'path','./plots', ...
            'noise_type',noise_type, 'noise_level',noise_level, ...
            'num_proj',num_proj, 'iter',iter, 'recompute',0, ...
            'proj_type',proj_type, 'prefix',prefix, 'plot_resid',0, ...
            'legend_cols',2, 'per_time',1);
          % call
          ma_run_and_plot(plt, arg, algs);
        end
      end
    end
  end
end

%% Per proj

phantoms =  {'ncat', 'mod-sl'}; {'mod-sl', 'ncat'}; {'ncat', 'mod-sl'}; {'mouse'}; {'ncat', 'mod-sl'};
num_projs = [15, 30, 60, 90, 180]; 
noises = { 
  struct('noise_type', 'poisson', 'noise_levels',[1e5])}; %, ... 5e4 1e4]), ...
%   struct('noise_type', 'gauss', 'noise_levels',[0.0 ])}; %.001 .003 .005 .01]) 
  
% noise_type = 'poisson'; 'poisson'; {'gauss'};
% noise_levels = 1e5; %[0, .005, .01, .05, .1]; %.001  1e5 for poisson
proj_types = {'fan'}; %{'fan', 'parallel', 'mouse'};
iter = 30;
prefix = 'max-snr-';
plt = 'per_num_proj';

for phantom = phantoms
  for noise = noises
    noise_type = noise{1}.noise_type;
    for noise_level = noise{1}.noise_levels
      for proj_type = proj_types
        % put args
        arg = struct('phan',phantom, 'phan_size',512, 'path','./plots', ...
          'noise_type',noise_type, 'noise_level',noise_level, ...
          'num_projs',num_projs, 'iter',iter, 'recompute',0, ...
          'proj_type',proj_type, 'prefix',prefix, 'plot_resid',0, ...
          'legend_cols',2, 'max_snr',1);
        % call
        ma_run_and_plot(plt, arg, algs);
      end
    end
  end
end

%% Per noise level

phantoms = {'ncat'}; {'ncat', 'mod-sl'}; {'mod-sl', 'ncat'}; {'ncat', 'mod-sl'}; {'mouse'}; {'ncat', 'mod-sl'};
num_proj = 90; [15, 30, 60, 90, 180]; 
noises = { 
%   struct('noise_type', 'poisson', 'noise_levels',[1e5]), ... 5e4 1e4]), ...
  struct('noise_type', 'gauss', 'noise_levels',[0 0.001 .005 .01 .05 .1])}; %.001 .003 .005 .01]) 
  
% noise_type = 'poisson'; 'poisson'; {'gauss'};
% noise_levels = 1e5; %[0, .005, .01, .05, .1]; %.001  1e5 for poisson
proj_types = {'fan'}; %{'fan', 'parallel', 'mouse'};
iter = 5;
prefix = '';
plt = 'per_noise_level';

for phantom = phantoms
  for noise = noises
    noise_type = noise{1}.noise_type;
    noise_levels = noise{1}.noise_levels;
    for proj_type = proj_types
      % put args
      arg = struct('phan',phantom, 'phan_size',512, 'path','./plots', ...
        'noise_type',noise_type, 'noise_levels',noise_levels, ...
        'num_proj',num_proj, 'iter',iter, 'recompute',0, ...
        'proj_type',proj_type, 'prefix',prefix, 'plot_resid',0, ...
        'legend_cols',2);
      % call
      ma_run_and_plot(plt, arg, algs);
    end    
  end
end


%% Plots of phantoms

phantoms = {'mouse'}; %, 'ncat', 'mod-sl'}; {'mod-sl', 'ncat'}; {'ncat', 'mod-sl'}; {'mouse'}; {'ncat', 'mod-sl'};
ranges = {[0 .15], [], []};
prefix = '';
plt = 'phantom';

for p = 1:length(phantoms)
  phantom = phantoms{p};
  
  % put args
  arg = struct('phan',phantom, 'phan_size',512, 'path','./plots', ...
    'prefix',prefix, 'range',ranges{p});
  % call
  ma_run_and_plot(plt, arg, {});
end


%%

addpath I:/temp/astra-1.7.1beta-src/matlab/tools/
addpath I:/temp/astra-1.7.1beta-src/bin/x64/Release/

arg = struct('phan','mod-sl', 'phan_size',512, 'path','./plots', ...
  'noise_type','gauss', 'noise_level',.001, ...
  'num_proj',15, 'iter',30, 'recompute',1, ...
  'proj_type','fan');
% call
ma_fig_periter(arg, algs(1:2));

%%
arg = struct('phan','mouse', 'phan_size',512, 'path','./plots', ...
  'noise_type','gauss', 'noise_level',.001, ...
  'num_proj',15, 'iter',30, 'recompute',1, ...
  'proj_type','mouse');
% call
ma_fig_periter(arg, algs(1));

%% Extracting the data

% PARTAG_SRCOBJDIST =395.730011  
% PARTAG_SRCDETDIST= 529.59  
% PARTAG_SCANANGLE=195.000000
% PARTAG_STARTANGLE=0
% PARTAG_PROJACQUIRED=196
% PARTAG_PROJRECON=195
% PARTAG_DETSIZEU=512
% PARTAG_DETSIZEV=256
% PARTAG_DETOFFSETU=4.000000 
% PARTAG_DETOFFSETV=0.000000 
% PARTAG_DETPITCHU=0.161760 
% PARTAG_DETPITCHV=0.161760
% PARTAG_CUBESIZEX=512
% PARTAG_CUBESIZEY=512
% PARTAG_CUBESIZEZ=512 
% PARTAG_CUBEPITCHX=0.12 
% PARTAG_CUBEPITCHY=0.12 
% PARTAG_CUBEPITCHZ=0.06 
% PARTAG_CUBEORIGINX=0 
% PARTAG_CUBEORIGINY=0 
% PARTAG_CUBEORIGINZ=0
% PARTAG_SCALEFACTOR= 600
% PARTAG_ROTATIONDIR=1  
% 
% OPTTAG_ZFILTER00 = 2
% OPTTAG_ZFILTER01 = 2
% OPTTAG_ZFILTER02 = 1
% OPTTAG_ZFILTER03 = 1
% OPTTAG_ZFILTER04 = 0
% OPTTAG_ZFILTER05 = 0
% OPTTAG_ZFILTER06 = 0
% OPTTAG_ZFILTER07 = 0
% OPTTAG_ZFILTER08 = 0
% OPTTAG_ZFILTER09 = 0
% OPTTAG_ZFILTER10 = 0
% OPTTAG_ZFILTER11 = 0
% OPTTAG_ZFILTER12 = 0
% OPTTAG_ZFILTER13 = 0
% OPTTAG_ZFILTER14 = 0
% OPTTAG_ZFILTER15 = 0
% OPTTAG_SLICESCALE = 1.5

pat = 'C:/Program Files (x86)/Exxim_Mouse_Example/raw.%04d';

sino = zeros(195, 512);
row = 128;
for i=0:194
  % read
  f = fopen(sprintf(pat, i), 'rb');
  im = fread(f, 256*512, 'int16');
  % reshape: it's row major
  im = reshape(im, 512,256)';
  % take the middle row
  sino(i+1, :) = im(row,:);
  fclose(f);
end
%
% read offset
offset_file = 'C:/Program Files (x86)/Exxim_Mouse_Example/offset';
offset = fread(fopen(offset_file, 'rb'), 256*512, 'int16');
offset = reshape(offset, 512,256)';
offset = offset(row, :);

% read air raw
airraw_file = 'C:/Program Files (x86)/Exxim_Mouse_Example/airraw';
airraw = fread(fopen(airraw_file, 'rb'), 256*512, 'int16');
airraw = reshape(airraw, 512,256)';
airraw = airraw(row, :);

% Correction
%   S (u,v) = log ( S_air(u,v) - S_offset(u,v) ) - log (S_prj_in(u,v) - S_offset(u,v) )
save phantoms/mouse-raw.mat sino airraw offset

%% Computing the GT volume

phan_size = 512;
det_size = 4/3; 0.16176;
num_det = 512;
sdd = 529.59 * (4/3) / .16176;
sid = sdd * (phan_size/2) / (num_det/2 * det_size); %395.730011;
proj_geom = astra_create_proj_geom('fanflat', det_size, num_det, ...
  (0:194)*pi/180 + pi/2, sid, sdd - sid); %2*pi
vol_geom = astra_create_vol_geom(phan_size, phan_size);

% projector
proj_id = astra_create_projector('line_fanflat', proj_geom, vol_geom);
  
pp = load('phantoms/mouse-raw.mat');
% get rid of negative values
% correction
air = bsxfun(@minus, pp.airraw, pp.offset);
% air(air < 0) = min(air(air > 0));

sino = bsxfun(@minus, double(pp.sino), pp.offset);
% sino(sino < 0) = 1;
sino = bsxfun(@minus, log(air), log(sino));

% copy last column
sino(:, end) = sino(:, end-1);
% sino(rows, cols) = repmat(log(air(cols)), length(rows), 1);
% sino(isinf(sino)) = min(sino(:));
% sino = log(60e3) - log(sino);
%   sino = sino - min(sino(:));
% shift left by 4 (detector offset)
ss = sino;
sino(:,1:end-4) = sino(:,5:end);
sino(:,end-3:end) = ss(:,1:4);
% sino(:,end-3:end) = min(sino(:));
%   sino = fliplr(sino);
sino(sino < 0) = 0;

% get weights wi
wi = exp(bsxfun(@minus, log(air), sino));

% multiply by 10 to make in cm^-1 
sino = sino * 10;
  

in_params = struct('vol_geom',vol_geom, 'proj_geom',proj_geom, ...
  'gt_vol',[], 'sino',sino, 'proj_id',proj_id, ...
  'wi',ones(size(sino)), 'fbp',[], 'prox_in',[]);

alg = 'SART';
alg_params = struct('iter',500, ...
    'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',.1, 'Lambda',1e3, 'ComputeIterationMetrics',0, ...
      'ClearReconstruction',1, 'UseBSSART',1));

P = ma_alg_astra(alg, in_params, alg_params);
astra_mex_projector('delete', proj_id);

phan_file = 'phantoms/mouse-sart-512.mat';
save(phan_file, 'P', 'sino', 'wi');
%%  
figure(3), imshow(P, []), colorbar
figure(2), hist(P(:), (0:.01:.3))


