%% Actual Shepp Logan phantom
SL = [  2   .69   .92    0     0     0   
        -.98 .6624 .8740   0  -.0184   0
        -.02 .1100 .3100  .22    0    -18
        -.02 .1600 .4100 -.22    0     18
         .01 .2100 .2500   0    .35    0
         .01 .0460 .0460   0    .1     0
         .01 .0460 .0460   0   -.1     0
         .01 .0460 .0230 -.08  -.605   0 
         .01 .0230 .0230   0   -.606   0
         .01 .0230 .0460  .06  -.605   0   ];
P = phantom(SL, 512);
save phantoms/sl-512.mat P
% imwrite(P, 'sl-256.png', 'BitDepth',16);

%% Modified Shepp-Logan
P = phantom(512);
save phantoms/mod-sl-512.mat P

%% Ncat
% How it was generated
% 	imgBig = read_ncat('nx', 1024, 'ny', 1024, 'marrow', true, ...
% 		'mu', [0 0.05 0.2 0.4 0.4 0.2]/0.2*1000); % True highres NCAT
% 	imgBig = single(imgBig) / single(max(imgBig(:))) * 0.4; % convert to 1/cm units

load phantoms/ncat-1024.mat
figure(1), imshow(P, [])

scale = 256;
P = imresize(P, scale / 1024, 'lanczos3');
figure(2), imshow(P, []), colorbar
save(sprintf('phantoms/ncat-%d.mat', scale), 'P')

%% Per iteration SNR for different # of projections
%

algs = {
  % ASTRA types
  %
  struct('name','SART', 'type','astra', ...
    'clr','k', 'lstyle','-', 'marker','d', ...
    'alg','SART', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',1, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0)))
      
  struct('name','SART-2', 'type','astra', ...
    'clr','k', 'lstyle','--', 'marker','d', ...
    'alg','SART', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',1.99, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0)))

%   struct('name','SART-0.5', 'type','astra', 'clr','-rd', ...
%     'alg','SART', ...
%     'alg_params', struct('iter',1, ...
%       'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
%       'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
%       'Alpha',0.5, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
%       'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
%       'UseBSSART',0)))
% 
%   struct('name','SART-0.1', 'type','astra', 'clr','-gd', ...
%     'alg','SART', ...
%     'alg_params', struct('iter',1, ...
%       'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
%       'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
%       'Alpha',0.1, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
%       'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
%       'UseBSSART',0)))
      
%   struct('name','SART-0.9', 'type','astra', 'clr','-gd', ...
%     'alg','SART', ...
%     'alg_params', struct('iter',1, ...
%       'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
%       'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
%       'Alpha',0.9, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
%       'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
%       'UseBSSART',0)))
%       
%   struct('name','SART-1.9', 'type','astra', 'clr','-bd', ...
%     'alg','SART', ...
%     'alg_params', struct('iter',1, ...
%       'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
%       'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
%       'Alpha',1.9, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
%       'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
%       'UseBSSART',0)))
      
%   struct('name','SART-PROX', 'type','astra', 'clr','-.k<', ...
%     'alg','SART-PROX', ...
%     'alg_params', struct('iter',1, ...
%       'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
%       'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
%       'Alpha',1, 'Lambda',1e1, 'ComputeIterationMetrics',1, ...
%       'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
%       'UseBSSART',0)))
      
  struct('name','BSSART', 'type','astra', ...
    'clr',[1 0.5 0], 'lstyle','-', 'marker','d', ...
    'alg','SART', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',1, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',1)))

  struct('name','BSSART-2', 'type','astra', ...
    'clr',[1 0.5 0], 'lstyle','--', 'marker','d', ...
    'alg','SART', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',1.99, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',1)))
      
  struct('name','ART', 'type','astra', ...
    'clr','r', 'lstyle','-', 'marker','s', ...
    'alg','ART', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',1, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0)))

	struct('name','ART-2', 'type','astra', ...
    'clr','r', 'lstyle','--', 'marker','s', ...
    'alg','ART', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',1.99, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0)))

  struct('name','SIRT', 'type','astra', ...
    'clr','b', 'lstyle','-', 'marker','x', ...
    'alg','SIRT', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',1, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0)))

  struct('name','SIRT-2', 'type','astra', ...
    'clr','b', 'lstyle','--', 'marker','x', ...
    'alg','SIRT', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',1.99, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0)))

	struct('name','BICAV', 'type','astra', ...
    'clr','g', 'lstyle','-', 'marker','*', ...
    'alg','BICAV', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',1, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0)))

	struct('name','BICAV-2', 'type','astra', ...
    'clr','g', 'lstyle','--', 'marker','*', ...
    'alg','BICAV', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',1.99, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0)))
      
  struct('name','OS-SQS', 'type','astra', ...
    'clr','m', 'lstyle','-', 'marker','^', ...
    'alg','OS-SQS', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',1, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0)))

%   struct('name','OS-SQS-0.5', 'type','astra', 'clr','-r^', ...
%     'alg','OS-SQS', ...
%     'alg_params', struct('iter',1, ...
%       'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
%       'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
%       'Alpha',0.5, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
%       'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
%       'UseBSSART',0)))
% 
%   struct('name','OS-SQS-0.1', 'type','astra', 'clr','-g^', ...
%     'alg','OS-SQS', ...
%     'alg_params', struct('iter',1, ...
%       'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
%       'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
%       'Alpha',.1, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
%       'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
%       'UseBSSART',0)))
      
  struct('name','CGLS', 'type','astra', ...
    'clr',[0.5 0.5 0.5], 'lstyle','-', 'marker','v', ...
    'alg','CGLS', ...
    'alg_params', struct('iter',1, ...
      'option',struct('UseMinConstraint',1, 'MinConstraintValue',0, ...
      'UseMaxConstraint',0, 'MaxConstraintValue',1, ...
      'Alpha',2, 'Lambda',1e3, 'ComputeIterationMetrics',1, ...
      'ClearReconstruction',1, 'UseJacobiPreconditioner',0, ...
      'UseBSSART',0)))      
  };

phantoms = {'ncat', 'mod-sl'};
num_projs = [15, 30, 60, 90, 180, 360];
noise_levels = [.001];
proj_types = {'fan'}; %{'fan', 'parallel'};

for phantom = phantoms
  for num_proj = num_projs
    for noise_level = noise_levels
      for proj_type = proj_types
        % put args
        arg = struct('phan',phantom, 'phan_size',512, 'path','./plots', ...
          'noise_type','gauss', 'noise_level',noise_level, ...
          'num_proj',num_proj, 'iter',30, 'recompute',1, ...
          'proj_type',proj_type);
        % call
        ma_fig_periter(arg, algs);
      end
    end
  end
end


%%

addpath I:/temp/astra-1.7.1beta-src/matlab/tools/
addpath I:/temp/astra-1.7.1beta-src/bin/x64/Release/

arg = struct('phan','mod-sl', 'phan_size',512, 'path','./plots', ...
  'noise_type','gauss', 'noise_level',.001, ...
  'num_proj',15, 'iter',30, 'recompute',1, ...
  'proj_type','fan');
% call
ma_fig_periter(arg, algs(1:2));

